### ISSUE TITLE
Devise is screwed up on heroku

### ISSUE THREAD

**Issue by dmcbrayer** [dmcbrayer/stripe_charger#12]
it won't deploy because now it's asking me to set the devise secret key.  I got no clue what to do.

**Comment by PendragonDevelopment** [comment]
You need to add the Devise secret key as an environment variable on Heroku.

On 3/26/2015 1:12 PM, Daniel McBrayer wrote:

> it won't deploy because now it's asking me to set the devise secret 
> key. I got no clue what to do.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/dmcbrayer/stripe_charger/issues/12.

## 

Jordan Burke
CTO/Lead Developer/Chief Dragon at Vitamin C
jordan@getvitaminc.com
(706) 424 - 3964
